### ISSUE TITLE
any function to do CLAHE ?

### ISSUE THREAD

**Issue by Forrestwang1** [aoles/EBImage#12]
Dear aoles,
Is there any function in this package to do CLAHE (contrast limited adaptive histogram equalization)? I know this following function only doing hist.eq for the whole image.
`equalize(x)`
Thanks,
Forrest

**Comment by aoles** [comment]
Hi,
thank you for your interest in *EBImage*! We don't have a function for doing  contrast limited adaptive histogram equalization implemented, but it should be in principle possible to integrate the code from https://github.com/erich666/GraphicsGems/blob/master/gemsiv/clahe.c into the package. May I ask what would be your use case of performing CLAHE?

Cheers,
Andrzej

**Comment by Forrestwang1** [comment]
Thanks for your quick reply! I have used EBImage for a while.  I am trying to use CLAHE for a project which is still related medial image. The function of equalize(x) is good for most of them, but sometimes some images really need CLAHE to enhance the picture.

**Comment by Forrestwang1** [comment]
I just opened the link which seems using C, I have no any knowledge about language C.  thanks anyway~ .

**Comment by aoles** [comment]
Thanks for your feedback!

I will then look into the possibility of adding a function for performing CLAHE based on the code from `clahe.c`, so stay tuned.

**Comment by Forrestwang1** [comment]
thanks so much for your consideration, I will wait for that and will check the package everyday~~,thanks again~

**Comment by aoles** [comment]
You're very welcome, I will keep you updated on the progress.

**Comment by Forrestwang1** [comment]
thanks~

**Comment by aoles** [comment]
Hi,
I'm happy to inform you that I've managed to integrate into *EBImage* [Karel Zuiderveld's implementation of CLAHE](https://github.com/erich666/GraphicsGems/blob/master/gemsiv/clahe.c). You can perform the filtering as follows.

Please let me know whether this works for you as expected.

Cheers,
Andrzej

```r
# input image containing multiple frames
x = readImage(system.file("images", "cells.tif", package="EBImage"))
display(x, method="raster", all=TRUE)

# perform contrast limited adaptive histogram equalization
y = clahe(x, nx=5, ny=5)
display(y, method="raster", all=TRUE)
```
![1](https://cloud.githubusercontent.com/assets/6545356/25011328/4517b428-206d-11e7-8acc-8b46457cb742.png)

![2](https://cloud.githubusercontent.com/assets/6545356/25011332/4894a606-206d-11e7-9152-5044b19898e1.png)

**Comment by Forrestwang1** [comment]
wow, you are so fast~ I cannot wait to try and thanks a lot!!!!!!!!!!!!!!!!!!!

**Comment by Forrestwang1** [comment]
It seems that I have trouble to update the package~any suggestion?

**Comment by aoles** [comment]
```r
# install.packages("devtools")
devtools::install_github("aoles/EBImage")
```

**Comment by Forrestwang1** [comment]
got it, thanks~~~~

**Comment by Forrestwang1** [comment]
this works so great, I tried randomly several images in my project, each shows a great result. Thanks, thanks~~~~`

**Comment by Forrestwang1** [comment]
Hey aoles,
I reinstalled R and tried several images again and it works perfect, thanks~
