### ISSUE TITLE
Check for points out-of-bounds in `floodFill` is incorrect

### ISSUE THREAD

**Issue by PKI-Kent** [aoles/EBImage#23]
The check for points out-of-bounds in `floodFill` (introduced in aefa504) is incorrect and may fail if the image is not square. The problem seems to be that `pt>dim(x)[1:2]` is computing `as.numeric(pt)>dim(x)[1:2]` which replicates `dim(x)` along the columns of `pt` rather than row-wise.

Here is a snippet which illustrates the problem:

``` r
# Points in the image
pt=matrix(c(100, 100, 50, 50), ncol=2)
pt
#>      [,1] [,2]
#> [1,]  100   50
#> [2,]  100   50

# Stand-in for dim(x)[1:2] - x is 200 x 75
dim_x = c(200, 75)

# Checking coordinates individually works fine
any(pt[,1]>dim_x[1])
#> [1] FALSE
any(pt[,2]>dim_x[2])
#> [1] FALSE

# Checking both coordinates at once fails
any(pt>dim_x)
#> [1] TRUE

# 100 > 200 ??
pt>dim_x
#>       [,1]  [,2]
#> [1,] FALSE FALSE
#> [2,]  TRUE FALSE

# The above seems to be equivalent to this:
alt = as.numeric(pt) > dim_x
dim(alt) = dim(pt)
alt
#>       [,1]  [,2]
#> [1,] FALSE FALSE
#> [2,]  TRUE FALSE
```

**Comment by PKI-Kent** [comment]
Here is a reprex using `floodFill` directly.

``` r
library(EBImage)
x = readImage(system.file("images", "shapes.png", package="EBImage"))
display(floodFill(x, c(67, 146), 0.5)) # OK
```

![](http://i.imgur.com/7aYL7S2.png)

``` r
display(floodFill(x, c(466, 72), 0.5)) # OK
```

![](http://i.imgur.com/RCPB7wp.png)

``` r
pts = rbind(c(67, 146), c(155, 66))
display(floodFill(x, pts, 0.5)) # OK
```

![](http://i.imgur.com/vyo3Cs7.png)

``` r
pts = rbind(c(67, 146), c(466, 72))
display(floodFill(x, pts, 0.5))
#> Error in floodFill(x, pts, 0.5): coordinates of starting point(s) 'pt' must be inside image boundaries
```

**Comment by aoles** [comment]
Good catch! Many thanks for your detailed report which was very helpful in fixing the bug. I've corrected the way of [checking for the out-of-boud points](https://github.com/aoles/EBImage/blob/9e6c2d3c8eb3f483c26f7aee150ea7b385947065/R/floodFill.R#L46-L47)  which should now work regardless of the image proportions and the input format of `pts`.
