### ISSUE TITLE
8-connected bwlabels

### ISSUE THREAD

**Issue by nickcee** [aoles/EBImage#30]
Hi,

Would it be possible to modify the bwlabels to take into account 8-connected pixels. As far as I can tell, it appears to only take into account 4-connected pixels.

Cheers,
Nick

**Comment by aoles** [comment]
Dear Nick,

thank you for reaching out. If I understand it correctly, you would like that the following sample objects touching at corners are considered as a single entity.
```r
library("EBImage")

# create sample image
img <- Image(dim = c(100, 100))
img[10:50, 10:50] <- img[51:90, 51:90] <- 1
display(img)
```
![image](https://user-images.githubusercontent.com/6545356/42170851-f6a87426-7e17-11e8-8e84-2a9380ef62ea.png)

There are no plans of modifying the current behavior of `bwlabels`. You might, however, use the `closing` filter with the minimal cross-shaped filter of size 3 to "bridge" the objects at the touching corner. This has minimal impact of the objects' shape while ensuring their connectivity.

```r
img <- closing(img, kern = makeBrush(3, "diamond"))
display(img)
```
![image](https://user-images.githubusercontent.com/6545356/42171716-53773de8-7e1a-11e8-8a33-72228b848e27.png)

Cheers,
Andrzej
