### ISSUE TITLE
Tolerance setting in watershed

### ISSUE THREAD

**Issue by SebastianKasan** [aoles/EBImage#36]
Hello there, 

can anyone here please explain to me, what the "tol" setting in the watershed segmentation does?
I have a hard time understanding the description in the package help.

Is this setting like in region-growing, a maximum feature distance between seed point and border pixel on the "ridgeline"? If so, why does it say that:
" If the height is smaller than the tolerance, the object will be combined with one of its neighbors, which is the highest"

That would mean that a pixel whose distance between seed and its own intensity is smaller than the threshold will be assigned to the neighbour?

Many thanks for your help!

**Comment by max-poltora** [comment]
@SebastianKasan, have you found the answer to your question? I am gathering information to understand this approach in watershed funciton too.

**Comment by SebastianKasan** [comment]
Yes I did. So imagine you have a small bump in a larger basin. Depending on this setting, the algorithm make the bump and individual basin or not.
That is at least how I remember it.
May I ask what you plan to do with it?
