### ISSUE TITLE
Improved viewer?

### ISSUE THREAD

**Issue by lajoimat** [aoles/EBImage#39]
Great package.
I really appreciate the display viewer, but it lacks a slider to adjust contrast & intensity...
A way to save the adjusted image or at least return the scaling factors would also be useful.
Any plans on further improvements?
Thanks!

**Comment by aoles** [comment]
Dear Mathieu,

thanks a lot for your feedback. The purpose of the image viewer is solely for displaying and visual inspection of data. It was never meant to be a tool for editing images, and providing a visual image editor is not the focus of the package. Thank you for your understanding. 

However, if you would like to work with images in an interactive fashion you can still build a [Shiny](http://shiny.rstudio.com)-based GUI around the package. The features you have mentioned should be relatively easily to implement. Feel free to have a look at [the CLAHE demo](https://github.com/aoles/CLAHE) to get an idea of this approach.


Cheers,
Andrzej
