### ISSUE TITLE
package ‘BiocManager’ is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by rafaleo** [aoles/EBImage#45]
> install.packages("BiocManager")
Warning in install.packages :
  package ‘BiocManager’ is not available (for R version 3.3.3)

Should I downgrade my installations or can wait for upgrade? Just need to test it for few things.

**Comment by aoles** [comment]
Please try:

```r
source("http://bioconductor.org/biocLite.R")
biocLite("EBImage")
```

Cheers,
Andrzej

**Comment by rafaleo** [comment]
Thanks! It's working.

**Comment by rafaleo** [comment]
Working this way:
```
source("http://bioconductor.org/biocLite.R")
biocLite("EBImage")
```
