### ISSUE TITLE
Have some issues with input values for floodfill

### ISSUE THREAD

**Issue by rafaleo** [aoles/EBImage#46]
I get error while trying to test the result on my data:
Error in EBImage::floodFill(x = matrix(c(rth[10008:10019, 1], rth[10008:10019,  : 
  coordinates 'pt' of the starting point(s) must be inside the image boundaries

I have over 10k points but just cut the snippet to check out if there's really point outside the matrix but could not find what's wrong.

```
 matrix(c(rth[10008:10019,1], rth[10008:10019,2]), ncol = 2, byrow = F)
          [,1]     [,2]
 [1,] 450689.5 363909.5
 [2,] 450691.5 363909.5
 [3,] 450693.5 363909.5
 [4,] 450695.5 363909.5
 [5,] 450697.5 363909.5
 [6,] 450699.5 363909.5
 [7,] 450701.5 363909.5
 [8,] 450703.5 363909.5
 [9,] 450705.5 363909.5
[10,] 450707.5 363909.5
[11,] 450709.5 363909.5
[12,] 450711.5 363909.5
> c(rth[10010,1], rth[10010,2])
       x        y 
450693.5 363909.5 
```
My starting point is in 3rd row of the input matrix. Why it's not seen by the function?

**Comment by aoles** [comment]
Could you please provide a MWE which I could use to reproduce the error? If possible, please consider using https://reprex.tidyverse.org/.

Cheers,
Andrzej

**Comment by rafaleo** [comment]
Ok. I know what may be the cause; probably I use wrong input, because I have an matrix which simulate pixels but there's no definition the point n.2 is the neighbor for n.3. 

Reproducible:
```
mat = matrix(c(c(450691, 363909), 
        c(450692, 363909),
        c(450693, 363909), 
        c(450694, 363909), 
        c(450695, 363909), 
        c(450695, 363908), 
        c(450701, 363909), 
        c(450711, 363909)), ncol = 2, byrow = F)

pt = c(450693, 363909)

ftest = EBImage::floodFill(x = mat, pt = pt, col = 1, tolerance = 0)
```
I guess I need to try to convert it to image or reach the original data.

**Comment by rafaleo** [comment]
I don't know how to make it work. I read `tif` using `raster`. If I place original data it's error `Error in validImage(x) : object must be an array`. While I convert to `Image` I get memory issues so can't test it. What should be the correct input?

**Comment by aoles** [comment]
Have you tried `readImage()`?

**Comment by rafaleo** [comment]
> im = readImage(paste0(locd, tfls[i]))
Error: cannot allocate vector of size 3.6 Gb
In addition: Warning messages:
1: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 33550 (0x830e) encountered
2: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 33922 (0x8482) encountered
3: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 34735 (0x87af) encountered
4: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 34736 (0x87b0) encountered
5: In readTIFF(x, all = all, ...) :
  TIFFReadDirectory: Unknown field with tag 34737 (0x87b1) encountered

I guess I need to get the raster data readable in that function because even if I `readImage` I need to make operations before use `floodFill`.

**Comment by rafaleo** [comment]
Ok. Found the bug in my data. Given a matrix from raster `m` which have format `m[,,1]` should be converted to `mi = EBImage::Image(m, c(1000, 1000))` - with dimensions given if not recognized from the source structure.

It works; `EBImage::floodFill(x = mi, pt = pt, col = 1)` gives an filled image on point, however, `plot(m)` (raster) and `plot(im)` (EBImage) have swap axis to each other.
