### ISSUE TITLE
watershed fails

### ISSUE THREAD

**Issue by felipenorconsult** [aoles/EBImage#63]
Hi

I am trying to perform watershed algorithm with 4 meters height threshold but it fails. 

> algo <- watershed(chm_s, th = 4)
Error in watershed(chm_s, th = 4) : unused argument (th = 4)

**Comment by aoles** [comment]
Hi, 

thanks for reaching out! Note that `th` is not a valid argument to `watershed`. Rather, the threshold is being set via `tolerance` in normalized units. Please refer to the function documentation `?watershed` for more details.

Cheers,
Andrzej
