### ISSUE TITLE
R Markdown: Error in validImage(x) : object must be an array

### ISSUE THREAD

**Issue by sagacitysite** [aoles/EBImage#7]
If I use R Markdown and I read an image using `readImage("lena.png")`, I get the following error:

**Error in validImage(x) : object must be an array**

Everything works perfect if I just use console or R file and it seems to be independent from the image (I tried another one in jpg format). Any idea what the problem could be?

**Comment by aoles** [comment]
Can you maybe share a reproducible example illustrating the issue? Thanks!

**Comment by sagacitysite** [comment]
To be honest: I can't reproduce.. if I create the same problem in a new R Markdown file, everything seems to work. I figured out that I also could solve it in the old file, I have changed the way setting the path (before it was `readImage("folder/lena.png")`, now I changed working directory one level deeper to "folder" and  `readImage("lena.png")` seems to work.. So the problem is not really solved, I have to choose a "hack", but that's okay in this case.

Therefore I think the problem is maybe not related to EBImage. I would close this issue now. If I found some other indications that it is related to EBImage and a way to reproduce it, I would open it again with new information.

Thanks a lot for your fast reply!

**Comment by aoles** [comment]
No worries - enjoy *EBImage*! :)

**Comment by rorynolan** [comment]
Hi guys, just a comment. I have found this error (kind of like you said) when nothing exists at the path that I've given. I think EBImage could do a better job of informing the user here, something like "file not found" would be much better. 
Thanks for EBImage @aoles, using it every day.
